name: Delete old workflow runs

on:

  workflow_dispatch:

    inputs:

      days: #要保留的天数

        description: '3'

        required: true

        default: 3

      runs: #要为每个yml保留的个数

        description: '8'

        required: true

        default: 8

jobs:

  del_runs:

    runs-on: ubuntu-latest

    steps:

      - name: Delete workflow runs

        uses: Mattraks/delete-workflow-runs@main

        with:

          token: ${{ secrets.GITHUB_TOKEN }}

          repository: ${{ github.repository }}

          retain_days: ${{ github.event.inputs.days }}

          keep_minimum_runs: ${{ github.event.inputs.runs }}


